### ISSUE TITLE
fuck this shit

### ISSUE THREAD

**Issue by Ooorange** [webpack-contrib/mini-css-extract-plugin#207]

**Comment by evilebottnawi** [comment]
@Ooorange This is not correct behavior

**Comment by ASiumkin** [comment]
> @Ooorange This is not correct behavior

You know what is incorrect behavior? It styles ordering change your plugin does!
Having a large project you cannot move to webpack 4 without messing up styles order is a bummer.
We have no alternative to mini-css-extract-plugin and the only advice you give developers is to rewrite the whole project because you decided to implement a different ordering than it had before.

So basically - you block a huge amount of people to upgrade from webpack 3 to webpack 4 and give absolutely zero f**ks about it

**Comment by alexander-akait** [comment]
@ASiumkin thanks for kind words, it motivates to help you more
