### ISSUE TITLE
Backslash in url() paths should be escaped

### ISSUE THREAD

**Issue by magnusriga** [webpack-contrib/mini-css-extract-plugin#270]
If a url() path in a CSS file contains backslash, `style-loader` will add another backslash in front (escaping it), which ensures it is treated as an actual path by browser.

`mini-css-extract-plugin` does not escape backslashes in url paths, when extracting CSS. In my opinion, it should do that, and thus work like style-loader does.

Minimal working example: https://github.com/magnusriga/mini-extract

**Reproduce issue:**
1. Open `webpack.config.js`
2. Turn off `mini-css-extract-plugin` and turn on `style-loader` (the lines are both there, ready to comment in/out)
3. Rebuild project
4. Check url path in CSS bundle, within main.js <-- It has two consecutive backslashes
5. Repeat 1-3 with `style-loader` off (commented out) and `mini-css-extract-plugin` on
6. If you now check the extracted CSS you will see that the url() paths now only have ONE backslash
7. **Result:** When browser tries to resolve the url() path, it will fail, because one backslash alone is interpreted as an escape character
8. **Conclusion:** `mini-css-extract-plugin` should escape backslashes like `style-loader` does

**Comment by evilebottnawi** [comment]
@magnusriga what is problem? `url()` have right value, `style-loader` change `url()` because your include this as part of `js` and it is require to rewrite `url()`, but when you extract you don't need rewrite `url()`. You use `outputPath` for `file-loader`, so `publicPath` can be change too, you need setup `publicPath` too in your case.
