### ISSUE TITLE
about SSR: document undefined

### ISSUE THREAD

**Issue by 8427003** [webpack-contrib/mini-css-extract-plugin#500]
👉🏽 Need support
I tried a ssr build work. It was almost perfect.
I try to build the code only once and use it on the client and server.
But when the server is running, I get an error: "document undefined". I know it is because it is getting css file through link tag. When on the server side, I want to skip this logic.

Can you add a string type option, which is a custom expression that helps skip this logic.
`` `
jump: "typeof document === 'undefined'? true: false"
`` `
change the code:
```
/******/ 	// The chunk loading function for additional chunks
/******/ 	__webpack_require__.e = function requireEnsure(chunkId) {
/******/ 		var promises = [];
/******/
/******/
/******/ 		// mini-css-extract-plugin CSS loading
/******/ 		var cssChunks = {"0":1};
/******/ 		if(installedCssChunks[chunkId]) promises.push(installedCssChunks[chunkId]);
/******/ 		else if(installedCssChunks[chunkId] !== 0 && cssChunks[chunkId]) {
...
```

to:
```
/******/ 	// The chunk loading function for additional chunks
/******/ 	__webpack_require__.e = function requireEnsure(chunkId) {
/******/ 		var promises = [];
/******/
/******/
/******/ 		// mini-css-extract-plugin CSS loading
/******/ 		var cssChunks = {"0":1};
                    
                         cons jump  =  typeof document === 'undefined'? true: false;
                         if(jump) {
                                // jump, do nothing
                         }
 		        else if(installedCssChunks[chunkId]) promises.push(installedCssChunks[chunkId]);
/******/ 		else if(installedCssChunks[chunkId] !== 0 && cssChunks[chunkId]) {
...

```

**Comment by evilebottnawi** [comment]
This plugin only for a browser environment, you will have other problem in future

**Comment by 8427003** [comment]
@evilebottnawi 
All assets processing plugins consider ssr as a necessity, like file-loader css-loader.
ok, I can only fork one for my puzzle

**Comment by evilebottnawi** [comment]
This plugin only for the browser environment, you file-loader + html generation for ssr

**Comment by evilebottnawi** [comment]
You can create minimum reproducible test repo and I show you how to set up that

**Comment by samkelleher** [comment]
Came across this thread and updating for anyone else who ends up here.

My use case is that I have an express app doing SSR, I needed to produce a regular CSS file that would be hosted by this express app. So I used MiniCssExtractPlugin to create the file. I didn't realise that the plugin not only creates the file, but bundles document loaders to inject the css link tag into a page header, which obviously does not apply on a server, hence the `document is undefined` exception is thrown as there is no document check made by this plugin for some reason.

I just need during development, for this file to be regenerated. There is no way to disable the document injection functionality that causes this error.

So during dev, I remove this plugin, and get it just to construct the file on build. If I need to work on that file, I add it back in.

While the plugin is in place, it breaks all HMR functionality due to the error.

I really recommend a document check, a one liner, to prevent the link element being added in non-browser environments.
