### ISSUE TITLE
1.3.0 broke usage with external-svg-sprite-plugin

### ISSUE THREAD

**Issue by mihkeleidast** [webpack-contrib/mini-css-extract-plugin#653]
- Operating System: Windows
- Node Version: 12.18.2
- NPM Version: 6.14.8
- webpack Version: 4.44.2
- mini-css-extract-plugin Version: 1.3.0

### Expected Behavior

Webpack build succeeds when using both mini-css-extract-plugin and [external-svg-sprite-loader](https://github.com/karify/external-svg-sprite-loader).

### Actual Behavior

Webpack build fails.

### Code

repo: https://github.com/mihkeleidast/webpack-css-svg-issue

### How Do We Reproduce?

See repo with repro.

I think #647 broke this.

**Comment by evilebottnawi** [comment]
Open an issue in external-svg-sprite-loader

**Comment by evilebottnawi** [comment]
Sorry, we can't do something on our side

**Comment by mihkeleidast** [comment]
Can you explain? Is the `module.content` external-svg-sprite-loader is trying to replace as string not guaranteed to be a string anymore? What is the expected type of `module.content`?

**Comment by evilebottnawi** [comment]
`Buffer`, I recommend do not rely on this, it is internal, but I think it will be buffer always and will not changed anymore

**Comment by bensampaio** [comment]
@evilebottnawi was this change introduced on 1.3.0? Do you have any suggestions on how to go around this issue?

The external-svg-sprite-loader relies on the `module.content` property because at the time the loader generates its output the SVG Sprite URL is not yet known. It is only possible to know the final URL after all SVG's were processed because the URL might include a `[contenthash]`. Therefore, during the optimize modules phase the plugin needs to replace the URL with `[contenthash]` to the actual URL with the generated hash. Do you see any other way around this issue?

**Comment by evilebottnawi** [comment]
@bensampaio Just `content.toString()`
