### ISSUE TITLE
Error: Module parse failed: Unexpected character '' - error of a single quotes in css file

### ISSUE THREAD

**Issue by tony-show** [webpack-contrib/mini-css-extract-plugin#667]
**Problem code of css file in node modules folder**
![image](https://user-images.githubusercontent.com/15953087/102353727-2278c200-3fb2-11eb-9fec-e23628788231.png)

**Console output error in build process**
![image](https://user-images.githubusercontent.com/15953087/102353122-50a9d200-3fb1-11eb-8c44-efa453bcdebc.png)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

You have invalid configuration double check `test`/`exclude`/`include`

JS parser try to parse CSS file
