### ISSUE TITLE
How extract SCSS? 

### ISSUE THREAD

**Issue by carlosalbertocruz** [webpack-contrib/mini-css-extract-plugin#705]
how to extract scss?

Is it possible to extract from .scss files?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started
