### ISSUE TITLE
SplitChunksPlugin fails to split during build

### ISSUE THREAD

**Issue by theninthsky** [webpack-contrib/mini-css-extract-plugin#850]
### Bug report
webpack build fails due to a change in mini-css-extract-plugin.

webpack: 5.58.0
mini-css-extract-plugin: 2.4.0

Relevant _webpack.config.js_ part:

```
splitChunks: {
        chunks: 'all',
        cacheGroups: {
          vendor: {
            test: /[\\/]node_modules[\\/]/,
            name: module => module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1]
          }
        }
      }
```

### Actual Behavior

The following errors is thrown during build:

`TypeError: Cannot read property '1' of null`

### Expected Behavior

Build should pass successfully.

### How Do We Reproduce?

Clone my repo and attempt to build:

https://github.com/theninthsky/flyingnotes-client/tree/9f5ad8717cb45f995855e363d745248f6b5637e9

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
Build works perfectly with version 2.3.0.

System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i3-8130U CPU @ 2.20GHz
    Memory: 834.43 MB / 3.91 GB
  Binaries:
    Node: 14.15.5 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
    Internet Explorer: 11.0.19041.1202
  Packages:
    babel-loader: ^8.2.2 => 8.2.2
    copy-webpack-plugin: ^9.0.1 => 9.0.1
    css-loader: ^6.3.0 => 6.3.0
    css-minimizer-webpack-plugin: ^3.1.1 => 3.1.1
    eslint-webpack-plugin: ^3.0.1 => 3.0.1
    html-webpack-plugin: ^5.3.2 => 5.3.2
    postcss-loader: ^6.1.1 => 6.1.1
    sass-loader: ^12.1.0 => 12.1.0
    webpack: ^5.58.0 => 5.58.0
    webpack-cli: ^4.9.0 => 4.9.0
    webpack-dev-server: ^4.3.1 => 4.3.1
    workbox-webpack-plugin: ^6.3.0 => 6.3.0

**Comment by twgraham** [comment]
I'd argue this should be reopened, I'll add some more context/debugging.

My webpack config for `splitChunks` is similar to @theninthsky here and #854 - I am trying to get my vendor chunks to have the file name `vendor.[lib name].[content hash].[extension]`. Prior to `2.4.0`, this would work correctly when matching on the `context`, so that vendor modules would have their own CSS chunks e.g. `codemirror` would become something like `vendor.codemirror.68d6118e42e2f4468d4c.css`.

Since `2.4.0`, css loaded from `node_modules` no longer contains the full context as it did before. See below examples comparing the modules before and after 2.4.0. Notice the context for CSS modules is truncated to the project root, instead of the containing directory of module.

### 2.3.0
<pre><code>CssModule {
  dependencies: [],
  blocks: [],
  parent: undefined,
  type: 'css/mini-extract',
  <strong>context: '/my-demo-project/node_modules/codemirror/lib',</strong>
  layer: null,
  needId: false,
  debugId: 6140,
  resolveOptions: {},
  factoryMeta: undefined,
  useSourceMap: true,
  useSimpleSourceMap: false,
  _warnings: undefined,
  _errors: undefined,
  buildMeta: {},
  buildInfo: {
    assets: [Object: null prototype] {},
    assetsInfo: Map(0) {},
    cacheable: true,
    hash: 'da78989ad053fea3f7f2c6195de31d2c'
  },
  _context: '/my-demo-project/node_modules/codemirror/lib',
  _identifier: '/my-demo-project/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!/my-demo-project/node_modules/codemirror/lib/codemirror.css'
}</code></pre>


### 2.4.0
<pre><code>CssModule {
  dependencies: [],
  blocks: [],
  parent: undefined,
  type: 'css/mini-extract',
  <strong>context: '/my-demo-project',</strong>
  layer: undefined,
  needId: false,
  debugId: 6477,
  resolveOptions: {},
  factoryMeta: undefined,
  useSourceMap: true,
  useSimpleSourceMap: false,
  _warnings: undefined,
  _errors: undefined,
  buildMeta: {},
  buildInfo: {
    assets: undefined,
    assetsInfo: undefined,
    cacheable: true,
    hash: 'da78989ad053fea3f7f2c6195de31d2c'
  },
  _context: '/my-demo-project',
  _identifier: '/my-demo-project/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].use[1]!/my-demo-project/node_modules/codemirror/lib/codemirror.css',
}
</code></pre>

**Comment by alexander-akait** [comment]
Can you provide small example, maybe regression on mini-css-extract-plugin side

**Comment by twgraham** [comment]
I'll try to create a demo repo by tomorrow.

**Comment by twgraham** [comment]
See the [demo repo here](https://github.com/twgraham/mini-css-extract-plugin-850). For convenience I've also run it in github actions [here](https://github.com/twgraham/mini-css-extract-plugin-850/runs/4451795542) so you can see the difference in output from `2.4.0` to `2.3.0`.

**Comment by isprogfun** [comment]
Can confirm, that we have a same issue after upgrading to the latest version. Disabling `experimentalUseImportModule` in the plugin config helps to solve it, but probably there should be another solution.

**Comment by koggdal** [comment]
Hi @alexander-akait!

I'm also experiencing this issue, and I put together a sample repo showing the unexpected result, the expected result, and a potential fix.

https://github.com/koggdal/sample-mini-css-extract-plugin-issue-850

Please have a look and let me know if you need to know anything more!

Thank you! 🙏
