### ISSUE TITLE
Disable css auto injection in document.head ?

### ISSUE THREAD

**Issue by daividh** [webpack-contrib/mini-css-extract-plugin#907]
Hello !

Is there a way to disable automatic injection in document.head ?
I'm developing a browser extension and want to only include style manually in the shadow root by injecting the URL of the extracted CSS. Actually, style is injected twice : automatically via document.head and manually in my shadow root.

Any advice ?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

I will reopen when you fix it and help you, please respect time of other developers, thanks
