### ISSUE TITLE
css order problem

### ISSUE THREAD

**Issue by TangJian-Eddie** [webpack-contrib/mini-css-extract-plugin#932]
Operating System: macOS 11.4
Node Version: 12.13.0
NPM Version: 6.12.0
webpack Version: 5.52.1
mini-css-extract-plugin Version: 1.16.2

### Bug report

when i upgraded mini-css-extract-plugin from 0.8.2 to 1.16.2, the css file order changed. But if i use style-loader, it will be the same.

### Actual Behavior

after build, the css file like this

```css
/* ComponentA style */
.A{}
/* ComponentB style */
.B{}
```

### Expected Behavior

it should be like this
```css
/* ComponentB style */
.B{} 
/* ComponentA style */
.A{}
```

### How Do We Reproduce?

ComponentA.ts
import B from './B'
import s from './A.module.scss'

ComponentB.ts
import s from './B.moduls.scss'

**Comment by TangJian-Eddie** [comment]
Because of the confidentiality, i can not share my code, but it can reproduce stably. The js file which after packing shows that import B before import style.

**Comment by TangJian-Eddie** [comment]
i just wondering why 0.8.2 won't have this problem, what can i do if i need to update it.

**Comment by alexander-akait** [comment]
Can you update to 2.6.0?

**Comment by TangJian-Eddie** [comment]
I'm sorry that i can not update it because we have so many projects. If we update it, it means that it is a large amount of work.

**Comment by TangJian-Eddie** [comment]
not only this project, other our projects' performances are the same. But i can not just reproduce it as a simple code. When i try to make a repository just like below, it's performance will be all right.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/60143213/164366810-261eaca8-48d8-466c-b410-61caf63c7679.png">

**Comment by TangJian-Eddie** [comment]
maybe you could tell me the possible reason, I can try to research it by myself.

**Comment by TangJian-Eddie** [comment]
Because it will be the right order when I use style-loader, I think the most possible reason will be this plugin. Maybe you can see the reason i don't recognize.

**Comment by alexander-akait** [comment]
Can you provide example of the problem (no need to show all code, just example, because using your code I can't reproduce)? Order is not guaranteed in some cases, especial if you have circular dependencies, but I strongly recommend try to update to v2 firstly, v1 is deprecated and not supported   

But I don't recommend to rely on order in that way, if you want to use classes in components (for example - react), please use CSS modules, so you can't have problems with classes overriding, or if you have vanilla CSS just create style.css and import it in top of your `application.js` (you can use `@import` in CSS if you want to split it ), also you can use additional entries to solve these problem too 

Also you can have non official plugins which breaks logic too

Hard to say without configuration/repo

**Comment by TangJian-Eddie** [comment]
Thanks for your answer. I have already found the answer of the question. The Function of sideEffects makes webpack get the wrong order so that the css order is wrong.

**Comment by ppfalling** [comment]
Can u express more the info about the reason? I have the same problem about css order too, 
![image](https://user-images.githubusercontent.com/39478818/181674342-67526a78-c8f9-4b43-8e34-2263739ca803.png)
here is my css, after build, it become order by letter, also the rules.
![image](https://user-images.githubusercontent.com/39478818/181674673-9b64fc33-fcfa-4b90-9a51-d815c331b81f.png)
