### ISSUE TITLE
will ABSOLUTE_PUBLIC_PATH("webpack:///mini-css-extract-plugin/") be appended with font url by default?

### ISSUE THREAD

**Issue by muthumanig** [webpack-contrib/mini-css-extract-plugin#936]
will ABSOLUTE_PUBLIC_PATH("webpack:///mini-css-extract-plugin/") be appended with font url by default?
eg: url(../fonts/) -> url(webpack:///mini-css-extract-plugin//fonts/)

**Comment by alexander-akait** [comment]
Please use the issue template

**Comment by yoannmoinet** [comment]
Hi there :wave:

Since it's the only mention of the issue from Google I'm commenting here so others may find a solution.

I had the same problem, with `mini-css-extract-plugin` version `2.6.0` and `webpack` version `5.72.1` where on the urls of external assets (fonts) there was this prefix of `webpack:///mini-css-extract-plugin/`.

I fixed it by setting `experimentalUseImportModule` to `false` in the plugin's options:

```javascript
new MiniCssExtractPlugin({
    experimentalUseImportModule: false
})
```

**Comment by yoannmoinet** [comment]
Created https://github.com/webpack-contrib/mini-css-extract-plugin/issues/945

**Comment by alexander-akait** [comment]
Closed in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/945
